#!/bin/bash

PROG=$(basename $0)

error() {
    echo -e "ERROR: $*" >&2
    exit 1
}

usage() {
    echo "USAGE: $PROG TARGET_DEV 1|2|PATH_TO_TAR.GZ"
}

if [[ $# -eq 2 ]]; then
    TARGET="$1"
    TARBALL_PATH="$2"
else
    usage && error "Incorrect number of arguments"
fi

# Ensure the target device's syntax is correct
[[ "$TARGET" =~ ^/dev/sd[a-z]$ ]] || error "Invalid target: $TARGET"
# Ensure bsdtar is installed
hash bsdtar 2>/dev/null || error "Please install bsdtar"
# Ensure script is being run as root
[[ $EUID -eq 0 ]] || error "This script must be run as root"

echo "You are about to erase $TARGET.  This is what $TARGET looks like according
to fdisk:"
fdisk -l $TARGET
echo
echo "Press return to continue, ^C to cancel"
read -s -n 1 key
if [[ $key != "" ]]; then
    error "Exiting..."
else
    echo
fi

# Run fdisk
echo "Running fdisk on $TARGET"...
sed -e 's/\([\+0-9a-zA-Z]*\)[ ].*/\1/' << EOF | fdisk $TARGET
o     #clear partition table
n     #new partition
p     #primary partition
1     #partition 1
      #start at beginning of disk
+100M #100 MiB boot parttion
t     #change type
c     #W95 FAT32 (LBA)
n     #new partition
p     #primary partition
2     #partition number 2
      #accept starting sector
      #accept ending sector
p     #print partition table
w     #write partition table
q     #quit
EOF
echo "Done."
echo

# Create FAT filestystem for /boot
echo "Making FAT filesystem"
mkfs.vfat "$TARGET"1
mkdir boot
mount "$TARGET"1 boot
echo "Done."
echo

# Create ext4 filestystem for /root
echo "Making ext4 filesystem"
mkfs.ext4 "$TARGET"2
mkdir root
mount "$TARGET"2 root
echo "Done."
echo

# Download/locate and un-tar tarball
echo "Finding tarball"
if [[ $TARBALL_PATH -eq 1 ]]; then
    echo "Downloading tarball"
    wget http://archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz
    echo "Extracting tarball"
    bsdtar -xpf ArchLinuxARM-rpi-latest.tar.gz -C root
elif [[ $TARBALL_PATH -eq 2 ]]; then
    wget http://archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz
    echo "Extracting tarball"
    bsdtar -xpf ArchLinuxARM-rpi-2-latest.tar.gz -C root
elif [[ -a $TARBALL_PATH ]]; then
    echo "Extracting tarball"
   bsdtar -xpf $TARBALL_PATH -C root
else
    echo $TARBALL_PATH
    error "Second argument must be 1, 2, or a valid path to the tarball"
fi
echo "Done.  Syncing..."
sync

# Move files in /root/boot to /boot
echo "Done.  Moving files to boot..."
mv root/boot/* boot
echo "Done.  Unmounting..."
umount boot root
echo "Done."
